# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14.4

    steps:
      - checkout

        # specify any bash command here prefixed with `run: `
      - run: ./test_all.sh
      - run: bash <(curl -s https://codecov.io/bash)
