version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      "fortio and grol":
        patterns:
          - "fortio.org/*"
          - "grol.io/*"
      "go x":
        patterns:
          - "golang.org/x/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
