# Build the binaries in larger image
FROM docker.io/fortio/fortio.build:v79@sha256:614de3fd5430a3502ab408f35a293e5cf1364695b6cc10a5168507ed519f55c2 AS build
WORKDIR /build
COPY . fortio
RUN make -C fortio official-build-version BUILD_DIR=/build OFFICIAL_TARGET=fortio.org/fortio/echosrv
# Minimal image with just the binary
FROM scratch
COPY --from=build /build/result/echosrv /usr/bin/echosrv
EXPOSE 8080
ENTRYPOINT ["/usr/bin/echosrv"]
