# Build the binaries in larger image
FROM docker.io/fortio/fortio.build:v78@sha256:a9ce421715f9c05a6441e187b227c42f76f3235318267838a3ba382570a5da69 AS build
WORKDIR /build
COPY . fortio
RUN make -C fortio official-build-version BUILD_DIR=/build OFFICIAL_TARGET=fortio.org/fortio/fcurl
# Minimal image with just the binary and certs
FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /build/result/fcurl /usr/bin/fcurl
ENTRYPOINT ["/usr/bin/fcurl"]
