# Gopkg.toml
#
# Initially from "dep init"
#

# DO NOT ADD MORE DEPENDENCIES TO FORTIO

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  revision = "c44066c5c816ec500d459a2a324a753f78531ae0" # before go 1.8 support drop
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.16.0" # 1.17 removes go 1.8 support

# Minimize vendor/

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
