# Gopkg.toml
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#

# DO NOT ADD MORE DEPENDENCIES TO FORTIO

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

# Minimize vendor/
[prune]
  go-tests = true
  unused-packages = true
  non-go = true
