# template for top level Makefile in tar ball distribution. used by "make dist" with variables prepended
# so the rest of the build works for debian without a git repo / from a tar ball

# dh_auto_build calls the default target, we don't need one
default:
	@echo "This is the build dist for fortio $(GIT_TAG)"
	@echo "please use the Makefile in src/fortio.org/fortio"

%:
	cd src/fortio.org/fortio; GOPATH=$(CURDIR) $(MAKE) $@ GIT_TAG=$(GIT_TAG) GIT_STATUS=$(GIT_STATUS) GIT_SHA=$(GIT_SHA)
