# template for top level Makefile in tar ball distribution. used by "make dist" with variables prepended
# so the rest of the build works for debian without a git repo / from a tar ball

%:
	cd src/fortio.org/fortio; GOPATH=$(CURDIR) make $@ GIT_TAG=$(GIT_TAG) GIT_STATUS=$(GIT_STATUS) GIT_SHA=$(GIT_SHA)
